version: '3.3'

networks:
  backend:
  traefik_net:
    external: true

services:
  wordpress:
    build: .
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${WORDPRESS_THEMES_VOLUME}:/var/www/html/wp-content/themes
      - ${WORDPRESS_PLUGIN_VOLUME}:/var/www/html/wp-content/plugins
      - ${WORDPRESS_UPLOAD_VOLUME}:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${WORDPRESS_URL}"
      - "traefik.docker.network=traefik_net"
    depends_on: 
      - database

  database:
    image: mysql:5.7
    volumes:
      - "${DB_VOLUME}:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on: 
      - database
    environment:
      PMA_HOST: database
    networks:
      - backend